language: go
sudo: false
go:
  - 1.10
  - 1.11
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - go get github.com/marcusolsson/tui-go
  - go get cloud.google.com/go/translate
  - go get github.com/atotto/clipboard
